import nodemailer from "nodemailer";

/**
 * Lazy-initialized nodemailer transporter.
 * Built from SMTP_* environment variables defined in .env.local.
 * We create it lazily (on first use) so the module can be imported safely
 * even before the env vars are available at build time.
 */
let _transporter = null;

function getTransporter() {
  if (!_transporter) {
    _transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST,
      port: Number(process.env.SMTP_PORT) || 587,
      secure: Number(process.env.SMTP_PORT) === 465, // true only for port 465
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
    });
  }
  return _transporter;
}

/**
 * Sends a one-time password email.
 *
 * This is the primary function wired into Better Auth's `emailOTP` plugin via
 * the `sendVerificationOTP` callback in `lib/auth.js`.
 *
 * @param {object} params
 * @param {string} params.email   - Recipient email address.
 * @param {string} params.otp     - The 6-digit OTP generated by Better Auth.
 * @param {string} params.type    - OTP purpose: "sign-in" | "email-verification" | "forget-password"
 */
export async function sendOtpEmail({ email, otp, type }) {
  const subject = getSubject(type);
  const body = getEmailBody({ otp, type });

  const transporter = getTransporter();

  await transporter.sendMail({
    from: `"ExamCell" <${process.env.SMTP_USER}>`,
    to: email,
    subject,
    html: body,
  });
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

function getSubject(type) {
  switch (type) {
    case "sign-in":
      return "Your ExamCell login OTP";
    case "email-verification":
      return "Verify your ExamCell email";
    case "forget-password":
      return "ExamCell password reset OTP";
    default:
      return "Your ExamCell OTP";
  }
}

function getEmailBody({ otp, type }) {
  const purpose = {
    "sign-in": "sign in to ExamCell",
    "email-verification": "verify your ExamCell email address",
    "forget-password": "reset your ExamCell password",
  }[type] ?? "complete your action";

  return `
    <div style="font-family: sans-serif; max-width: 480px; margin: 0 auto;">
      <h2 style="color: #1a1a2e;">ExamCell — One-Time Password</h2>
      <p>Use the OTP below to ${purpose}. It expires in <strong>10 minutes</strong>.</p>
      <div style="
        display: inline-block;
        font-size: 2rem;
        font-weight: bold;
        letter-spacing: 0.3rem;
        padding: 12px 24px;
        background: #f0f4ff;
        border-radius: 8px;
        color: #1a1a2e;
        margin: 16px 0;
      ">${otp}</div>
      <p style="color: #666; font-size: 0.875rem;">
        If you did not request this OTP, you can safely ignore this email.
      </p>
    </div>
  `;
}
